from __future__ import annotations

from app.database import models as database_models


def test_core_database_tables_are_registered() -> None:
    expected_tables = {
        "ai_conversation_messages",
        "ai_conversations",
        "ai_inference_logs",
        "ai_model_configurations",
        "ai_models",
        "ai_provider_health",
        "ai_providers",
        "ai_settings",
        "api_keys",
        "attack_paths",
        "ai_governance_records",
        "campaigns",
        "assessments",
        "confidence_scores",
        "audits",
        "controls",
        "decision_records",
        "executive_dashboards",
        "executive_decisions",
        "executive_forecasts",
        "executive_kpis",
        "executive_recommendations",
        "executive_reports",
        "executive_trends",
        "department_settings",
        "audit_logs",
        "compliance_reports",
        "evidence_records",
        "evaluation_metrics",
        "evaluation_runs",
        "evidence",
        "graph_edges",
        "graph_nodes",
        "directory_entries",
        "departments",
        "employees",
        "findings",
        "iocs",
        "hallucination_records",
        "feature_flags",
        "mitre_mappings",
        "notifications",
        "organizations",
        "organization_settings",
        "frameworks",
        "permissions",
        "refresh_tokens",
        "recommendations",
        "reasoning_traces",
        "policy_versions",
        "policies",
        "risk_projections",
        "risk_register",
        "threat_actors",
        "threat_correlations",
        "threat_evidence",
        "threat_hunts",
        "threat_recommendations",
        "role_permissions",
        "roles",
        "tenants",
        "trust_scores",
        "team_settings",
        "sessions",
        "system_settings",
        "teams",
        "user_preferences",
        "user_profiles",
        "user_roles",
        "users",
    }

    assert expected_tables.issubset(set(database_models.Base.metadata.tables))
