import type { NavigationItem } from "@/types/ui";

export const publicNavigation = [
  { label: "Login", href: "/login" },
  { label: "Register", href: "/register" },
  { label: "Forgot Password", href: "/forgot-password" },
  { label: "Magic Link", href: "/magic-link" },
] satisfies NavigationItem[];

export const protectedNavigation = [
  { label: "Dashboard", href: "/dashboard" },
  { label: "Executive", href: "/executive" },
  { label: "SOC Center", href: "/soc-center" },
  { label: "Alerts", href: "/alerts" },
  { label: "Incidents", href: "/incidents" },
  { label: "Cases", href: "/cases" },
  { label: "Investigations", href: "/investigations" },
  { label: "Threat Center", href: "/threat-center" },
  { label: "Intel", href: "/intel" },
  { label: "IOCs", href: "/iocs" },
  { label: "Assets", href: "/assets" },
  { label: "Evidence", href: "/evidence" },
  { label: "Playbooks", href: "/playbooks" },
  { label: "Attack", href: "/attack" },
  { label: "MITRE", href: "/mitre" },
  { label: "Workbench", href: "/workbench" },
  { label: "Tenants", href: "/tenants" },
  { label: "Workspaces", href: "/workspaces" },
  { label: "Organizations", href: "/organizations" },
  { label: "Departments", href: "/departments" },
  { label: "Teams", href: "/teams" },
  { label: "Users", href: "/users" },
  { label: "Roles", href: "/roles" },
  { label: "Permissions", href: "/permissions" },
  { label: "Groups", href: "/groups" },
  { label: "Invitations", href: "/invitations" },
  { label: "Sessions", href: "/sessions" },
  { label: "API Keys", href: "/apikeys" },
  { label: "Service Accounts", href: "/service-accounts" },
  { label: "SSO", href: "/sso" },
  { label: "MFA", href: "/mfa" },
  { label: "Audit", href: "/audit" },
  { label: "Profile", href: "/profile" },
  { label: "Settings", href: "/settings" },
  { label: "Administration", href: "/administration" },
] satisfies NavigationItem[];
