// Dashboard landing page composing the enterprise dashboard framework only.
import { AreaChart, Activity, Clock3, Layers3, ServerCog } from "lucide-react";

import { DashboardShell } from "@/dashboard/layouts/dashboard-shell";
import { DashboardWidgetGrid } from "@/dashboard/widgets/widget-grid";
import { dashboardWidgets } from "@/dashboard/core/dashboard-models";
import { DashboardCard, HoverCard, MetricCard, SummaryCard, StatusCard } from "@/dashboard/cards/dashboard-cards";

export default function DashboardPage(): React.JSX.Element {
  return <DashboardShell className="pb-6"><div className="space-y-6"><DashboardCard title="Executive workspace" description="Framework-only enterprise dashboard composition with reusable modules."><div className="grid gap-4 lg:grid-cols-4"><MetricCard title="Workspaces" description="Multi-tenant selectors and context-aware navigation"><Kpi icon={<Layers3 className="h-5 w-5" />} value="06" label="Workspace ready" /></MetricCard><MetricCard title="Systems" description="Module shells and panel surfaces"><Kpi icon={<ServerCog className="h-5 w-5" />} value="14" label="Shared modules" /></MetricCard><MetricCard title="Activity" description="Timeline, feed, and event surfaces"><Kpi icon={<Activity className="h-5 w-5" />} value="24" label="Recent events" /></MetricCard><MetricCard title="Response" description="Motion-enabled cards and widgets"><Kpi icon={<AreaChart className="h-5 w-5" />} value="98%" label="Responsive ready" /></MetricCard></div></DashboardCard><div className="grid gap-6 xl:grid-cols-[1.1fr_0.9fr]"><HoverCard title="Widget grid" description="Drag-ready and resizable widget layout primitives."><DashboardWidgetGrid widgets={dashboardWidgets} /></HoverCard><SummaryCard title="Dashboard summary" description="UI shell for future module composition only."><div className="grid gap-4 sm:grid-cols-2"><StatusCard title="Status" description="Shell state is healthy." /><StatusCard title="Motion" description="Framer Motion transitions enabled." /><StatusCard title="Accessibility" description="ARIA, focus, and keyboard affordances included." /><StatusCard title="Performance" description="Lazy-load ready and composition-first." /></div></SummaryCard></div><div className="grid gap-6 xl:grid-cols-2"><DashboardCard title="Module placeholders" description="Frontend-only entry points for future dashboard modules."><div className="grid gap-3 sm:grid-cols-2"><ModuleLink href="/threat-center" title="Threat Center" description="Static UI shell" /><ModuleLink href="/soc-center" title="SOC Center" description="Static UI shell" /><ModuleLink href="/fraud-center" title="Fraud Center" description="Static UI shell" /><ModuleLink href="/risk-center" title="Risk Center" description="Static UI shell" /><ModuleLink href="/compliance-center" title="Compliance Center" description="Static UI shell" /><ModuleLink href="/administration" title="Administration" description="Static UI shell" /></div></DashboardCard><DashboardCard title="Shared layout surfaces" description="Cards, tables, charts, filters, panels, timeline, and activity modules are framework-only."><div className="grid gap-3 sm:grid-cols-2"><ModuleLink href="/reports" title="Report shell" description="UI only" /><ModuleLink href="/audit-logs" title="Audit logs" description="UI only" /><ModuleLink href="/integrations" title="Integrations" description="UI only" /><ModuleLink href="/assets" title="Assets" description="UI only" /></div></DashboardCard></div></div></DashboardShell>;
}

function Kpi({ icon, value, label }: { icon: React.ReactNode; value: string; label: string }): React.JSX.Element {
  return <div className="rounded-2xl border border-line bg-canvas p-4"><div className="flex items-center justify-between text-muted">{icon}<span className="text-xs uppercase tracking-wide">KPI</span></div><div className="mt-3 text-3xl font-semibold">{value}</div><div className="mt-1 text-sm text-muted">{label}</div></div>;
}

function ModuleLink({ href, title, description }: { href: string; title: string; description: string }): React.JSX.Element {
  return <a href={href} className="rounded-2xl border border-line bg-panel p-4 transition hover:-translate-y-0.5 hover:shadow-soft"><div className="text-sm font-semibold text-text">{title}</div><div className="mt-1 text-sm text-muted">{description}</div></a>;
}
